<a href="https://colab.research.google.com/github/ABHISHEKKUMAR-MOURYA123/8.09.24-python/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
np.arange(1,9)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
np.arange(1,101,3)

array([  1,   4,   7,  10,  13,  16,  19,  22,  25,  28,  31,  34,  37,
        40,  43,  46,  49,  52,  55,  58,  61,  64,  67,  70,  73,  76,
        79,  82,  85,  88,  91,  94,  97, 100])

In [ ]:
np.arange(3,24,3)

array([ 3,  6,  9, 12, 15, 18, 21])

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
np.zeros(100,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
np.random.randn(3,5)

array([[-0.4980689 ,  0.79947931, -0.93409721, -0.39540692,  0.45718244],
       [ 0.59480895, -0.08963307,  0.61382387,  0.62564641, -0.0110079 ],
       [-0.10343066,  0.30631852,  0.80830467,  0.82035994,  0.66310307]])

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.linspace(0,2,5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [ ]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [ ]:
np.random.rand(3,5)

array([[0.15956589, 0.42625303, 0.19410131, 0.96605446, 0.01808125],
       [0.14013338, 0.71731043, 0.42419788, 0.19039751, 0.63605718],
       [0.21924062, 0.21536356, 0.21310169, 0.79492403, 0.57782107]])

In [ ]:
np.random.randint(0,10,50)

array([9, 2, 7, 7, 3, 2, 5, 9, 0, 8, 5, 5, 6, 8, 6, 1, 6, 6, 9, 5, 3, 5,
       0, 8, 0, 5, 0, 0, 5, 9, 0, 6, 1, 6, 6, 2, 1, 8, 4, 4, 9, 5, 7, 9,
       8, 2, 6, 3, 1, 5])

In [ ]:
Sample_aray=np.arange(0,30)
Sample_aray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [ ]:
Sample_aray.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [ ]:
Sample_aray.reshape(10,9)

ValueError: cannot reshape array of size 30 into shape (10,9)

In [ ]:
Sample_aray[6]

6

In [ ]:
Sample_aray[60]

IndexError: index 60 is out of bounds for axis 0 with size 30

In [ ]:
Sample_aray[5:10]

array([5, 6, 7, 8, 9])

In [ ]:
Sample_aray[0]=[100]

ValueError: setting an array element with a sequence.